### ISSUE TITLE
tensorflow model to Barracuda or Onnx

### ISSUE THREAD

**Issue by JonasX99** [Syn-McJ/TFClassify-Unity-Barracuda#10]
I would like to know if it would be possible to get a [Teachable Machine](https://teachablemachine.withgoogle.com/) model into Unity and use it with Barracuda Currently I have tried to convert a Tensorflow model with tensorflow_to_barracuda.py which I get this error: google.protobuf.message.DecodeError: Error parsing message

I have also tried to convert the model with the [tf2onnxt](https://github.com/onnx/tensorflow-onnx) but when I have successfully convert the model and import it the model has warnings

also when I import any model of my own the camera is responding every second

-Unity version 2020.1
-Barracuda version have tried with 0.4.0 and 0.6.3

Hope Teachable Machine models is possible to use since it's fast and easy for the project i am working on

**Comment by Syn-McJ** [comment]
@JonasX99 I haven't tried teachable machine, but importing tensorflow model and convering it should work fine, but keep in mind that I only managed to do it with a limited number of architectures (see blogpost). If you provide more details about your model (or the model itself), I can see what might be wrong with it.
________________________________

**Comment by JonasX99** [comment]
@Syn-McJ  This is the [model](https://drive.google.com/drive/folders/1r9npbC_TtV9W6pfh5xoVNVG27zfHLLaC?usp=sharing) but on [Teachable Machine](https://teachablemachine.withgoogle.com/) it is possible to export the model in many ways but I haven't had any luck with it yet. I just wanted to know if it is even possible with [Teachable Machine](https://teachablemachine.withgoogle.com/) :)
