### ISSUE TITLE
Combining object detection with AR

### ISSUE THREAD

**Issue by vishnuvardhan2005** [Syn-McJ/TFClassify-Unity-Barracuda#12]
Hi,

I am trying to use this for object detection. I want to combine this with AR. For example, on detecting a object DOG, instead of drawing a bounding box, I want to show a animation in that area. I don't have good knowledge on Unity as I am using it for the first time. Is it possible? If yes, can you point to any references that would be helpful

**Comment by Syn-McJ** [comment]
@vishnuvardhan2005 
That is something I'm interested in myself, but don't have time currently to research. So no, I don't know the exact way to do that. I'd say using ARFoundation, it should be possible to raycast into a center of a box to determine the approximate position of an object.

Sorry I can't be of more help.
