### ISSUE TITLE
barracuda not success to convert the pb file

### ISSUE THREAD

**Issue by HolyShitKillingMachine** [Syn-McJ/TFClassify-Unity-Barracuda#2]
I am downing the ml-agents file from the github link you provide,and use anaconda prompt to cd to the destination of converter.py,and type the code ,python tensorflow_to_barracuda.py my.pb destination the output destination,And it cames out that there is no mlagents module.
I donot know why

**Comment by Syn-McJ** [comment]
@HolyShitKillingMachine,
 You need to download the whole repo to use this script. Alternatively, you can try to install mlagents from pip like `pip install mlagents`.

**Comment by Pouyan97** [comment]
@HolyShitKillingMachine Easier way to transform tensorflow to barracuda is by just downloading the whole repo in [this link](https://github.com/Unity-Technologies/barracuda-release). 
Then move your tensorflow model 'my.pb' to barracuda-release/Tools folder.
`cd barracuda-release/Tools` to get to the Tools folder 
and then just run `python tensorflow_to_barracuda.py my.pb output.*`
