### ISSUE TITLE
Not working on Android

### ISSUE THREAD

**Issue by AliciaPose** [Syn-McJ/TFClassify-Unity-Barracuda#6]
The project seems to work in my laptop but when I compile the apk and try to run it in my Android smartphone (Xiaomi Redmi Note 7), it inmediately crushes. Here I present a screenshot of the app when I point at my laptop. The image randomly crops and duplicates and everything start to shake. Why might this be happening? Thank you.
![WhatsApp Image 2020-04-20 at 11 27 53](https://user-images.githubusercontent.com/61687118/79739738-e136f200-82fe-11ea-8644-916d711dda7e.jpeg)

**Comment by Syn-McJ** [comment]
@AliciaPose 
Can't say without actually testing it on the same device, which I cannot do at the moment. On my Galaxy S8 it works fine.
