### ISSUE TITLE
Covert a cyclegan model to barracuda

### ISSUE THREAD

**Issue by pengyumic** [Syn-McJ/TFClassify-Unity-Barracuda#8]
Hi, I have been trying to deploy a cyclegan model into unity with Barracuda, but I have failed many times. I have tried different methods and other pretrained models from Internet. Usually the errors like missing layers(I am not sure if this will affect the usage of the model, I have one converted successfully to nn with missing layers, but failed when run on Android), -1 not supported by lamda...  I am actually having no experiences in neural network, so I am kind of struggling now. Any suggestions? I have tried tensorflowsharp too, I cannot even compile it with ARcore. Are there any other plugins that I should shoot for?

**Comment by Syn-McJ** [comment]
@pengyumic 
Barracuda is in early preview and it might not support some operations that your models are using. If you have an issue with converting a model, you should probably open an issue here: https://github.com/Unity-Technologies/barracuda-release

Also, check my answer on a similar question:
https://github.com/Syn-McJ/TFClassify-Unity-Barracuda/issues/7#issuecomment-619517400
